---

docker_image: opensyllabus/osp-pipeline
docker_name: osp-pipeline

# spark-defaults.conf
# -------------------

spark_master_port: 7077
spark_master_url: spark://{{ spark_master_host }}:{{ spark_master_port }}

spark_tasks_per_core: 10

spark_default_parallelism: '{{
  spark_worker_count|int *
  spark_worker_vcpus|int *
  spark_tasks_per_core
}}'

spark_packages:
  - org.apache.hadoop:hadoop-aws:2.7.5

spark_executor_memory: 400g
spark_driver_memory: 24g
spark_driver_cores: 4
spark_task_max_failures: 10
spark_local_dir: /mnt/spark

spark_hadoop_fs_s3a_connection_maximum: 1500

spark_speculation: true
spark_speculation_interval: 5000ms
spark_speculation_multiplier: 100

spark_executor_heartbeat_interval: 10s
spark_network_timeout: 120s

# spark-env.sh
# ------------

# Use EC2 public DNS.
spark_public_dns: >
  `wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname ||
   wget -q -O - http://169.254.169.254/latest/meta-data/local-ipv4`

spark_max_files: 100000
