---

dependencies:

  - role: python

  - role: supervisor

    supervisor_programs:

      - name: rqworker

        command: >
          {{ scraper_src_dir }}/env/bin/rqworker
          --config osp_scraper.settings.rq
          --worker-class {{ scraper_worker_class }}

        numprocs: '{{ scraper_concurrency }}'

        config:
          directory: '{{ scraper_src_dir }}'
          autostart: true
          killasgroup: true
          stopasgroup: true
